### ISSUE TITLE
Clear up utils.jl

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#111]
These moments seems that they don't really belong here anymore:
https://github.com/FourierFlows/FourierFlows.jl/blob/6e87e0421fd67fe1521691c2d3af82577d2dd53e/src/utils.jl#L258-L266

Possibly other things should/could be cleared out from `utils.jl`.

**Comment by glwagner** [comment]
Agreed.

**Comment by navidcy** [comment]
If we are to keep them, we should generalize `xmoment` and `ymoment` to work for grids where `dx`≠`dy`. (From what I understand the moment definition as it stands it assumes `dx`=`dy`.)

**Comment by glwagner** [comment]
I don't think it assumes `dx=dy`, does it? It assumes that the grid spacing is uniform though. 

should we just nuke these or put them somewhere? I don't know where to put them unfortunately... but we could just put them in our 2nd favorite package: `GeophysicalFlows`

**Comment by navidcy** [comment]
OK, my bad. Indeed it does not assume `dx=dy`. They are OK as is.

If these function should be somewhere then it'll be here because one might wanna use them, e.g., from PassiveTracerFlows.jl or other packages.
