### ISSUE TITLE
An instance of Output() function can never be called

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#117]
@glwagner ,

I think that as the code stands now this instance can never be called (because the code calls simply the Output constructor with these arguments).

https://github.com/FourierFlows/FourierFlows.jl/blob/6b45bac10a3ab4368eec550623b5bf2aff4335c4/src/output.jl#L32-L36

Am I wrong? None of the tests in `test_output.jl` manages to call these lines...

Fix or delete?

**Comment by glwagner** [comment]
Hmm. This function should be an inner constructor inside the definition of the Output struct. 

https://pkg.julialang.org/docs/julia/THl1k/1.1.1/manual/constructors.html#Inner-Constructor-Methods-1
