### ISSUE TITLE
Automatic GPU tests with gitlab.com/JuliaGPU

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#127]
With the new GPU direction we should add the automatic travis-like test for GPU using Gitlab.

@glwagner can you attend this? It shouldn't be too difficult. You (and by this I don't necessarily mean *you* personally...) seem to have done it for [Oceananigans.jl](https://gitlab.com/JuliaGPU/Oceananigans-jl/commits/master). FourierFlows.jl is already in JuliaGPU at gilab.

Next should come [GeophysicalFlows.jl](https://github.com/fourierFlows/GeophysicalFlows.jl).

**Comment by glwagner** [comment]
We can ask. `Oceananigans.jl` was added because we are collaborating with julia lab (julia lab is being partially funded by the same project). I'm not sure how open the resource is, but I'll ask.

**Comment by navidcy** [comment]
> Edit: but let's wait until we have full-fledged GPU functionality, I think?

But it would be helpful if we had the test while developing the code *towards* full-fledged GPU functionality..

**Comment by navidcy** [comment]
#130 addresses this issue
