### ISSUE TITLE
CUDAnative.exp instead of Base.exp when using GPU?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#140]
When running tests on GPU we get warnings like

```julia
┌ Warning: calls to Base intrinsics might be GPU incompatible
│   exception =
│    You called exp(x::T) where T<:Union{Float32, Float64} in Base.Math at special/exp.jl:75, maybe you intended to call exp(x::Float64) in CUDAnative at /home/navid/.julia/packages/CUDAnative/Phjco/src/device/cuda/math.jl:98 instead?
│    Stacktrace:
│     [1] exp at special/exp.jl:75
│     [2] #25 at /home/navid/.julia/packages/GPUArrays/1wgPO/src/broadcast.jl:49
└ @ CUDAnative ~/.julia/packages/CUDAnative/Phjco/src/compiler/irgen.jl:116
```

Perhaps in fact indeed we want to be using CUDAnative.exp when running on the GPU instead of Base.exp. How can we do it? Overload `exp` function with `CUDAnative.exp` inside `CuFourierFlows.jl`? (Similarly for Base.sin, Base.cos, ...)

**Comment by ali-ramadhan** [comment]
Not sure where `exp` is being called but I think if you use GPUifyLoops.jl and the call to `exp` is inside an `@loop`, then GPUifyLoops will use Casette to rewrite the loop to use `Base.exp` or `CUDAnative.exp` depending on whether you're running on a CPU or GPU.

**Comment by navidcy** [comment]
thanks @ali-ramadhan, I'll look into GPUifyLoops.jl

`exp` is used in making the exponential wavenumber filter
https://github.com/FourierFlows/FourierFlows.jl/blob/c3be73f13973d5893afd0e368f99483cb0d55f7f/src/domains.jl#L330-L337
and in the ETDRK4 timestepper
https://github.com/FourierFlows/FourierFlows.jl/blob/c3be73f13973d5893afd0e368f99483cb0d55f7f/src/timesteppers.jl#L508-L518

**Comment by ali-ramadhan** [comment]
Ah I see. If `filt` or `expLdt` is only computed once then stored then you can probably just compute it on the CPU and convert to `ArrayType` (`Array` or `CuArray`).

But if it's performance critical then writing a GPUifyLoops kernel might be the way to go. You could probably also look into using Cassette.jl directly but I couldn't figure out how to really use it (not much documentation either lol).

**Comment by navidcy** [comment]
I think this is stale and we should close it. @glwagner?

**Comment by glwagner** [comment]
I agree. `CUDA.jl` may also have solutions for this now but I'm not sure.
