### ISSUE TITLE
Timestepper overhaul

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/FourierFlows.jl#18]
We need to restart / finish the time-stepper overhaul. These are the issues that should be addressed:

1. The function `get_etd_coeffs` is not as general or well-written as it could be.

2. I believe that all "helper" functions (like `get_etd_coeffs`) should be moved to the top of the file. The time-stepper definitions can then go below. This may improve code readability.

3. The time-stepper definitions / constructors are too restrictive. Many of them explicitly require 2- or 3-dimensional solution arrays, which is unnecessary. We should use [type parameterization](https://docs.julialang.org/en/stable/manual/types/#Parametric-Types-1) to generalize these definitions.

4. The syntax used in the step-forward functions is inconsistent (regarding the use of `@.`, mostly), and sometimes not as efficient as it could be. For example, I believe that the algorithm

```
a .= b .+ c
a .*= d
```

is *less efficient* than
```
a .= d .* (b .+ c)
```

The reason is because in the first example, the compiler does not know that it can pass the values of d, b, c to the processor simultaneously. I think in the second example, the compiler may be able to produce faster code that sends the values of all 3 array to the processors for an operation, thus consolidating and perhaps reducing memory-transfer operations. I'm not 100% sure I'm right about this, but we can test it.

5. In order to make these changes, we need to construct a convenient test (like a forward run of the McWilliams problem that extracts values of the solution at particular points). It would be even better if the test could compare some 'original' version of FourierFlows with an updated version...

**Comment by ChrisRackauckas** [comment]
>The reason is because in the first example, the compiler does not know that it can pass the values of d, b, c to the processor simultaneously. I think in the second example, the compiler may be able to produce faster code that sends the values of all 3 array to the processors for an operation, thus consolidating and perhaps reducing memory-transfer operations. I'm not 100% sure I'm right about this, but we can test it.

That's loop fusion and that is true. It really wouldn't do much though.
