### ISSUE TITLE
overload @show for Params, Vars, Problem, TimeStepper

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#191]
We should overload `@show` for `Params` and `Vars` struct.
Can we loop over the contents of a struct, e.g., `Params` and printout all it's content variable names?

**Comment by glwagner** [comment]
Something along the lines of

```julia
print(io, Tuple("$p: $(getproperty(params, p)\n" for p in propertynames(params))...)
```

might do it

**Comment by navidcy** [comment]
#192 added some `show()` overloads; I'm closing this.
