### ISSUE TITLE
Testing for physics

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/FourierFlows.jl#20]
We need to figure out how to test physics. For example, we need to have a test for ```twodturb.jl``` which does something like: 

1) loads an initial condition from file
2) runs a simulation
3) compares with some saved output
4) determines that the simulation is accurate within a specified tolerance

Generating the initial condition and output is not difficult, but determining what tolerance is acceptable is hard. The tolerance may have to do with the number of timesteps taken. 

Having such a test would speed up testing new features substantially, since we would then be free to make changes to time steppers (or even introduce new ones!)

**Comment by navidcy** [comment]
Some physics tests were added for `twodturb` and `barotropicqg` modules. In particular:
- a Lamb-dipole test, `test/test_twodturb.jl` 
- a Rossby wave test, `test/test_barotropicqg.jl`
