### ISSUE TITLE
cxeltype() and fleltype() being used?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#207]
Are these legacy?

https://github.com/FourierFlows/FourierFlows.jl/blob/280289fc427be0a9f54ad4e2e0e270d8847779e5/src/utils.jl#L29-L30

**Comment by glwagner** [comment]
Remove them and see if tests pass?

**Comment by glwagner** [comment]
I don't think they are legacy. In hindsight, they are not a good idea. But removing them probably requires a bit of code restructuring. It wouldn't be a bad thing, but we should do more than just delete these functions. I believe they are used, for example, for determining the underlying floating point type of a complex number.

**Comment by navidcy** [comment]
Simple search all .jl files didn’t show that they were used...

**Comment by navidcy** [comment]
Simple search all .jl files didn’t show that they were used...

**Comment by navidcy** [comment]
Simple search all .jl files didn’t show that they were used...

**Comment by navidcy** [comment]
Tests pass -- see #208
