### ISSUE TITLE
a suggestion on the docs

### ISSUE THREAD

**Issue by francispoulin** [FourierFlows/FourierFlows.jl#218]
I am pretty new to Julia and was excited to come accross your library.

I was going through the docs and discovered that using the two  lines to define a grid don't work without first statin that we are using FourierFlows.  Maybe it's evident but thought I would suggest maybe adding this to the docs, to make it easier for the beginner.

```
julia> nx, Lx = 64, 2π;

julia> grid = OneDGrid(nx, Lx)
ERROR: UndefVarError: OneDGrid not defined
Stacktrace:
 [1] top-level scope at REPL[2]:1

julia> using FourierFlows

julia> grid = OneDGrid(nx, Lx)
OneDimensionalGrid
  ├─────────── Device: CPU
  ├──────── FloatType: Float64
  ├────────── size Lx: 6.283185307179586
  ├──── resolution nx: 64
  ├── grid spacing dx: 0.09817477042468103
  └─────────── domain: x ∈ [-3.141592653589793, 3.0434178831651124]

```

**Comment by glwagner** [comment]
@francispoulin thank you! I agree --- its nice to have docs that are complete enough to be copy / pasted into a julia terminal.

Are you suggesting a change to a specific part of the docs, or something new? If you're suggesting a change, let me know the lines you're referring to and I can work on improving them. 

If something new, if you suggest where the new addition would be helpful I can work on adding it.

**Comment by francispoulin** [comment]
the docs are great and thanks for putting them together.

I guess a simple fix would be to have a line saying "using FourierFlows" at the very beginning.  You have it in the linear shallow water example and that all runs.  I know since I just did it line by line.  Very nice code by the way!  So easy to read.  

On a very different note, you don't happen to have a one-layer QG model floating around do you? I am tempted to put one together but thought I would ask first, just in case it would save a fit of time.

**Comment by glwagner** [comment]
@francispoulin do you mind if we keep this issue open ? I think it's a nice suggestion and I hope we get around to addressing it!

**Comment by glwagner** [comment]
@francispoulin as for one-layer QG, I think we refer to that as a "barotropic QG" model over at `GeophysicalFlows.jl` (which contains implementations of a few geophysically-relevant equation sets using `FourierFlows.jl`):

https://fourierflows.github.io/GeophysicalFlowsDocumentation/dev/generated/barotropicqg_betadecay/

**Comment by francispoulin** [comment]
Certainly!  Sorry for closing it. 

Thanks for the link and I was just typing a response as I foudn your other library.  Thanks for sharing all of it's and it's great to play with.
