### ISSUE TITLE
__precompile__() ?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#26]
Should we remove the `__precompile__()` headers from most of the `.jl` files?
Our initial intention was to have them so as to speed-up tests in the development.

**Comment by glwagner** [comment]
I don't think so, because I think we want everything to precompile, rather than recompiling every time we call "using FourierFlows". Unless I'm confused about what __precompile__() does...

**Comment by ChrisRackauckas** [comment]
Yes, it should really just be in one place on the top of the package module.

**Comment by glwagner** [comment]
Thanks Chris, that's very helpful and will save us some clutter. I think I was confused about what a "dependency" of a Julia module is.

**Comment by navidcy** [comment]
Done.
