### ISSUE TITLE
Julia 0.7 compatibility

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#28]
At some point we should make sure the code is compatible with Julia 0.7. For the moment it does not pass the julia 0.7 tests.

**Comment by glwagner** [comment]
Do you know which tests are failing / what changes are needed?

**Comment by navidcy** [comment]
For example this fails from `domains.jl`:
```julia
julia> Base.DFT.FFTW.cFFTWPlan{Complex{Float64}, -1, false, 2}
ERROR: UndefVarError: cFFTWPlan not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:14
 [2] top-level scope```

**Comment by glwagner** [comment]
I think the FFTW package is changing in 0.7; the default fft tools may not have the full FFTW tools. We may need to add `import FFTW` somewhere, or something.

**Comment by navidcy** [comment]
Some remarks:

With `FFTW.jl` we only have to prepare fft-plans for forward transforms. Then, in-place transform are done using, e.g.
```julia
mul!(fhat, g.rfftplan, f)  # rfft of a real-valued array f
ldiv!(f, g.rfftplan, fhat)  # irfft
```

**Comment by navidcy** [comment]
PR #81 addresses all changes needed for `v0.7` and also `v1.0`. I'm closing the issue.
