### ISSUE TITLE
Should we be using `CUDA.CUFFT` on GPUs?

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#309]
https://juliagpu.gitlab.io/CUDA.jl/usage/array/#FFTs

**Comment by glwagner** [comment]
Don't we use `CUFFT` when we call `fft(a::CuArray)`? That's what those docs say.

**Comment by navidcy** [comment]
Well, we construct fft plans. But we don't use `CUDA.CUFFT.plan_ffr` but rather `FFTW.plan_fft` I think.

https://github.com/FourierFlows/FourierFlows.jl/blob/0aef7bcb8c255617469f0a3fde23e3c57ddd78ae/src/CuFourierFlows.jl#L2-L3

Shouldn't we be using `CUDA.CUFFT.plan_fft` and `CUDA.CUFFT.plan_rfft` instead? Btw, `effort` kwarg is allowed there...

**Comment by navidcy** [comment]
Btw, latest CUDA.jl seems to have broken something....
https://buildkite.com/julialang/fourierflows-dot-jl/builds/213#e0fcfca5-415c-48c3-8b0b-56aad944ec65/252-450

**Comment by navidcy** [comment]
> Well, we construct fft plans. But we don't use `CUDA.CUFFT.plan_ffr` but rather `FFTW.plan_fft` I think.
> 
> https://github.com/FourierFlows/FourierFlows.jl/blob/0aef7bcb8c255617469f0a3fde23e3c57ddd78ae/src/CuFourierFlows.jl#L2-L3
> 
> Shouldn't we be using `CUDA.CUFFT.plan_fft` and `CUDA.CUFFT.plan_rfft` instead? Btw, `effort` kwarg is allowed there...

OK, don't bother.

Under the hood FFTW calls `CUDA.CUFFT.plan_fft`...

**Comment by glwagner** [comment]
Right!

**Comment by glwagner** [comment]
> Btw, latest CUDA.jl seems to have broken something.... https://buildkite.com/julialang/fourierflows-dot-jl/builds/213#e0fcfca5-415c-48c3-8b0b-56aad944ec65/252-450

Ok, let's pin CUDA.

**Comment by navidcy** [comment]
Did it already! :)
But want to figure out what happened also.
