### ISSUE TITLE
`FilteredLSRK54TimeStepper` appears to be missing

### ISSUE THREAD

**Issue by apaloczy** [FourierFlows/FourierFlows.jl#359]
The filtered form of `LSRK54TimeStepper` seems to be missing (also broken link in the docs: [https://fourierflows.github.io/FourierFlowsDocumentation/previews/PR356/timestepping/](https://fourierflows.github.io/FourierFlowsDocumentation/previews/PR356/timestepping/)). I'm happy to open a PR adding it.

**Comment by navidcy** [comment]
Note that the link you posted above is for a docs preview. But the problem you described exist in the dev version of the docs.

**Comment by apaloczy** [comment]
> Note that the link you posted above is for a docs preview. But the problem you described exist in the dev version of the docs.

I see. Is there anything specific about filtering in `LSRK54TimeStepper`?

**Comment by navidcy** [comment]
None that I’m aware of

**Comment by navidcy** [comment]
Actually the `FilteredLSRK54TimeStepper` was never even defined! I opened a PR.
