### ISSUE TITLE
BarotropicQG module

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#38]
With topography present, viscosity diffuses topography. This needs to be resolved. Viscosity should act only on relative vorticity, not on topography.

**Comment by glwagner** [comment]
Isn't that easy to fix? Just change so the prognostic variable is relative vorticity ζ rather than ζ+h or whatever it is.

**Comment by navidcy** [comment]
Yes it should be — I’ll look into it and make a PR.

**Comment by navidcy** [comment]
This issue (and more) are fixed in #42. I'm closing the issue.
