### ISSUE TITLE
Adding a "State" Composite Type

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/FourierFlows.jl#39]
I think we need a new Composite Type called, for example, `State`

Right now, the 'problem agnostic' fields `t` and `sol` are contained in the `Vars` type. I think we should move these to a new type, defined perhaps in `FourierFlows.jl` or somewhere equivalently appropriate. Something like

```
mutable struct State{dim} <: AbstractState
    t::Float64
    sol::Array{Complex{Float64},dim}
    step::Int
end
```

and

```
mutable struct DualState{dimc,dimr} <: AbstractState
    t::Float64
    solc::Array{Complex{Float64},dimc}
    solr::Array{Complex{Float64},dimr}
    step::Int
end
```

Then the call signature for `calcN!` would be `calcN!(N, sol, t, v, p, g, s)` where `s` is a variable of type `State`.

We would also add `State` to the `Problem` type. 

Or maybe `ProblemState` and `DualProblemState`. Something like that. This would require extensive changes to all the modules as well as `timesteppers.jl`, but I bet I could complete it all in an hour or too. Thoughts?

**Comment by navidcy** [comment]
This was implemented with #40; I'm closing the issue.
