### ISSUE TITLE
Proposed test for twodturb (or any module really)

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#51]
@oliasselin mention to me a way to test `twodturb` (and in principle any physics) 

Say we want to write a test for some physics that we don't really know an analytical solution. Take `twodturb` as an example:
`∂ζ/∂t + J(ψ,ζ) = ν Δζ.`

The procedure goes as follows: Assume there exist an analytical solution in closed form `ζ_guess(x,y,t)=...` (you can take any guess that satisfies the  boundary conditions). Plug then this guess back into the equation and compute the residual `R(x,y,t)` _analytically_. Then add this residual as a forcing on the r.h.s.:
`∂ζ/∂t + J(ψ,ζ) = ν Δζ + R.`
Now your guessed solution is _actually_ a solution of the forced problem.  If, for simplicity, you guess a steady solution `ζ_guess(x,y)` then time-stepping `∂ζ/∂t + J(ψ,ζ) = ν Δζ + R` starting from rest should lead you to `ζ(x,y,t)=ζ_guess`.

Given that you have computed `R` analytically if indeed the forced problem converges to your guessed solution it means that all other terms in the equation were coded correctly.

**Comment by glwagner** [comment]
That makes sense. We can only test algorithms with forcing this way, but we can also use it to test timesteppers. Just a modification on what you said: `ζ_guess` doesn't have to be a *solution* to the problem. It's just an arbitrary time-dependent function.

Either way, I think it'd be good to have a 1D grid so we can do these tests efficiently.

**Comment by navidcy** [comment]
I meant "assume that this is a solution". If it is actually a solution then R=0.

**Comment by glwagner** [comment]
I don't think any assumptions need to be made. It just has to be a function that satisfies the boundary conditions.

**Comment by navidcy** [comment]
Man, it's just the way I phrased it. I didn't mean anything other from what you are saying. Show some mercy fpr the non-native English speaker.

**Comment by glwagner** [comment]
There is no mercy!

**Comment by navidcy** [comment]
#52 implements such a test.
