### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#59]
We need to add more detailed documentation. Specifically, we need to add documentation for:
- `traceradvdiff` module
- `verticallyfourierboussinesq` module
- `verticallycosineboussinesq` module
At its current state the documentation only includes the equation(s) each module solve.

We should also include some documentation explaining how the code is structures. For example, explaining the hierarchy among `AbstractGrid`, `AbstractParams`, `AbstractVars`, `AbstractEquation`, `AbstractTimeStepper`, and `AbstractProblem` types.

Also, we need to document the `cuda` version of the code.

Last, we need to add somewhere in the documentation the discussion on stochastic forcing implementation and proper calculation of energy budgets.

**Comment by navidcy** [comment]
#71 adds some notes on forcing and in particular discusses the differences between Ito and Stratonovich cacluli

#73 adds more details for the `TwoDTurb` module

**Comment by navidcy** [comment]
#79 adds more details for the `TracerAdvDiff` module but still there is more needed

**Comment by glwagner** [comment]
Closing because I think we've made significant progress.
