### ISSUE TITLE
QL mode in BarotropicQG

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#72]
@glwagner:

So I coded up the QL equations in `BarotropicQG`. Do you think I should include them inside `BarotropicQG` or add a new module `BarotropicQGQL`?

Including them in `BarotropicQG` module would make the module more cumbersome.
Also should we really add a new module for QL in the code? It's not the most widely used equations. Is there a way we have a separate repo with modules we use and add the `BarotropicQGQL` there? That way only people who want to use QL would load it.

**Comment by glwagner** [comment]
This is an issue for GeophysicalFlows.jl.
