### ISSUE TITLE
New Interpolations release

### ISSUE THREAD

**Issue by timholy** [FourierFlows/FourierFlows.jl#83]
Interpolations recently released a [new, breaking release](https://github.com/JuliaMath/Interpolations.jl/blob/master/NEWS.md)---see https://github.com/JuliaMath/Interpolations.jl/pull/226 for details.

This package appears to be affected by the bounds-checking change. I recently [placed an upper bound for the package manager](https://github.com/JuliaLang/METADATA.jl/pull/18101) on your behalf, but if you want to continue following the development of Interpolations you may need to make changes. Sorry for any inconvenience.

**Comment by glwagner** [comment]
Thanks @timholy! Our code broke because the bounds-check exposed a (thankfully minor) bug! I suppose it was a sensible change.

https://github.com/FourierFlows/FourierFlows.jl/pull/84 fixes this issue.

**Comment by timholy** [comment]
Great! That was kind of the point of making those into errors, I'm glad it's already paying off.
