### ISSUE TITLE
README badge is broken

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/FourierFlows.jl#91]
The README claims that "Julia v0.7 v0.1.0 Tests fail". This is not what it should say.

How was this badge generated and how can we fix it?

**Comment by navidcy** [comment]
I was just asking in slack to try to figure this out.
We should just remove the badges for the moment; I'm trying to figure this out.

**Comment by navidcy** [comment]
A temporary fix is to put a link to something like this:
https://s3.ap-south-1.amazonaws.com/juliarun-ci/4b9c7a80dfbe2bca33de8811119687335d0fe838/FourierFlows_reverse_dependency_tests.html

**Comment by glwagner** [comment]
I didn't have the nerve to delete the badge... but I did clean it up a little bit [here](https://github.com/FourierFlows/FourierFlows.jl/tree/FixREADMEBadges). I feel less stressed, that's a win.

**Comment by glwagner** [comment]
Fixed by PR #93.
